default: &default
  adapter: postgresql
  encoding: utf8
  username: <%= ENV.fetch("DB_USERNAME") { 'postgres' } %>
  password: <%= ENV.fetch("DB_PASSWORD") { 'password' } %>
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling

development:
  <<: *default
  database: proxycrawl_development

test:
  <<: *default
  database: proxycrawl_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
